### PR TITLE
Handle optional values properly

### PR DESCRIPTION
**Pull request by thomaseizinger**
This series of patches handles optional values in various situations properly.

It is an updated version of https://github.com/jplatte/serde_html_form/pull/4.

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
Can you add one more test case? 😅

A struct with a `Vec<String>` field should have the field deserialized to `vec!["", "test"]` for the input `field=&field=test`.

**Comment by thomaseizinger** [comment]
> Can you add one more test case? sweat_smile
> 
> A struct with a `Vec<String>` field should have the field deserialized to `vec!["", "test"]` for the input `field=&field=test`.

Done!

**Comment by thomaseizinger** [comment]
I added one more that I think makes sense!

**Review by jplatte — APPROVED** [review]
I must admit I don't 100% understand how it all works, but the fact that only the two `deserialize_option` methods were changed makes me very confident that there are no weird accidental behavior changes from this.

**Comment by jplatte** [comment]
Thanks a lot for finding such a good and clean solution and covering it with lots of tests! :)

**Comment by thomaseizinger** [comment]
> I must admit I don't 100% understand how it all works, but the fact that only the two `deserialize_option` methods were changed makes me very confident that there are no weird accidental behavior changes from this.

I think apart from dtolnay himself, nobody really 100% understands how serde works.

**Comment by jplatte** [comment]
This has been released in v0.1.1 :)

**Pull request merged**
